POST http://localhost:5001/api/auth/new
content-type: application/json

{
    "name": "Andres",
    "email": "andres@gmail.com",
    "password": "123456"
}

###

POST http://localhost:5001/api/auth
content-type: application/json

{
    "email": "andres@gmail.com",
    "password": "123456"
}

###

GET http://localhost:5001/api/auth/renew
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMDczMjkyLCJleHAiOjE2MjAwODA0OTJ9._vw9ehjEDUrFoRmTXGPxk9NiwWwYikAHIyOC7aQDG1k
