@token: 123

POST http://localhost:5001/api/auth/new
content-type: application/json

{
    "name": "Andres",
    "email": "andres@gmail.com",
    "password": "123456"
}

###

POST http://localhost:5001/api/auth
content-type: application/json

{
    "email": "andres@gmail.com",
    "password": "123456"
}

###

GET http://localhost:5001/api/auth/renew
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMTQ3NTEzLCJleHAiOjE2MjAxNTQ3MTN9.AF3OQMxv2pqZXuyaTNinFtDB95O8Dh1m03YjyXU-4cg

###


GET http://localhost:5001/api/events
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMTQ3NTEzLCJleHAiOjE2MjAxNTQ3MTN9.AF3OQMxv2pqZXuyaTNinFtDB95O8Dh1m03YjyXU-4cg



###

POST http://localhost:5001/api/events
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMTQ3NTEzLCJleHAiOjE2MjAxNTQ3MTN9.AF3OQMxv2pqZXuyaTNinFtDB95O8Dh1m03YjyXU-4cg

{
    "title": "Titulo de la nota",
    "notes": "Soy las notas",
    "start": 0,
    "end": "Tue May 04 2021 20:39:25 GMT+0200 (hora de verano de Europa central)"
}

###

POST http://localhost:5001/api/events/212335
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMTQ3NTEzLCJleHAiOjE2MjAxNTQ3MTN9.AF3OQMxv2pqZXuyaTNinFtDB95O8Dh1m03YjyXU-4cg

###

DELETE http://localhost:5001/api/events/:id
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMTQ3NTEzLCJleHAiOjE2MjAxNTQ3MTN9.AF3OQMxv2pqZXuyaTNinFtDB95O8Dh1m03YjyXU-4cg
