

POST http://localhost:5001/api/auth/new
content-type: application/json

{
    "name": "Andres",
    "email": "andres@gmail.com",
    "password": "123456"
}

###

POST http://localhost:5001/api/auth
content-type: application/json

{
    "email": "andres@gmail.com",
    "password": "123456"
}

###

GET http://localhost:5001/api/auth/renew
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMjM0NjQxLCJleHAiOjE2MjAyNDE4NDF9.Mjt9qqba-R9rZI0ilRJFJLWSs0Rn7qVr7Asbo_HcN6Y

###


GET http://localhost:5001/api/events
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMjM0NjQxLCJleHAiOjE2MjAyNDE4NDF9.Mjt9qqba-R9rZI0ilRJFJLWSs0Rn7qVr7Asbo_HcN6Y



###

POST http://localhost:5001/api/events
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMjM0NjQxLCJleHAiOjE2MjAyNDE4NDF9.Mjt9qqba-R9rZI0ilRJFJLWSs0Rn7qVr7Asbo_HcN6Y

{
    "title": "trabajosssss de la nota",
    "notes": "Soy las notas",
    "start": 0,
    "end": 100000
}

###

POST http://localhost:5001/api/events/6091b1c1447c9f530e2caa1a
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMjM0NjQxLCJleHAiOjE2MjAyNDE4NDF9.Mjt9qqba-R9rZI0ilRJFJLWSs0Rn7qVr7Asbo_HcN6Y

{
    "title": "ahora si que i",
    "notes": "oye",
    "start": 0,
    "end": 100000
}
###

DELETE http://localhost:5001/api/events/6091b1c1447c9f530e2caa1a
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MDkwMzAxMjYxNzY2NDM1NmU5NDA2OGUiLCJuYW1lIjoiQW5kcmVzIiwiaWF0IjoxNjIwMjM0NjQxLCJleHAiOjE2MjAyNDE4NDF9.Mjt9qqba-R9rZI0ilRJFJLWSs0Rn7qVr7Asbo_HcN6Y
